on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        default: "Aryan"
        required: true
      city:
        default: "Delhi"
        required: true
      country:
        default: "India"
        required: true

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!" ${{ github.event.inputs.name }}
      - name: List files
        run: ls -la
      - name: Checkout
        run: actions/checkout@v2
