name: Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # for the manual execution


jobs:
  test-and-build:
    name: test-and-build
    runs-on: ubuntu-latest
    
    strategy:
       matrix:
         node-version: [18.x,20.x,22.xx]
